version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  test_bot:
    image: multilogin/test_bot:latest
    ports:
      - "5000:5000"
